<?php

namespace Test\SpojeNet\Realpad;

use SpojeNet\Realpad\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-10-10 at 15:55:50.
 */
class ExceptionTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $client = new \SpojeNet\Realpad\ApiClient();
        $client->doCurlRequest('https://realpadsoftware.com/cs/');
        $this->object = new Exception('Test Message', $client);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    /**
     * @covers SpojeNet\Realpad\Exception::getErrorMessage
     */
    public function testgetErrorMessage()
    {
        $this->assertEquals('', $this->object->getErrorMessage());
    }

    /**
     * @covers SpojeNet\Realpad\Exception::getErrorMessages
     */
    public function testgetErrorMessages()
    {
        $this->assertEquals('', $this->object->getErrorMessages());
    }
}
