#!/bin/sh
set -e

case "$1" in
    configure)
       composer install  -d /usr/lib/realpad2mailkit/
       composer-global-update deb/realpad-takeout
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
